title: 🕶 Ain't Nobody Here but Us
theme: minima
logo: nobody.png

header_pages: 
   - Drawing .md
   - Investment .md
   - Nutrition .md
   - Writing .md
   - Character .md


minima:
  social_links:
    twitter: jekyllrb